### ISSUE TITLE
Code not using language variables for checking

### ISSUE THREAD

**Issue by Pablohn26** [ivanhercaz/CanaryBot#3]
[This line](https://github.com/ivanhercaz/CanaryBot/blob/master/fullstopschecker.py#L435) uses harcoded language strings instead of language variables. This breaks the functionality for future added languages.

**Comment by ivanhercaz** [comment]
Thank you very much, @Pablohn26! Issue fixed with 13f203e. I tested it in the test mode and it works fine :)
